"use client"
import 'bootstrap/dist/css/bootstrap.min.css'
import "./globals.css";
import Nav from './components/nav/nav';
import Head from 'next/head';
import useDocumentTitle from '../hooks/useDocumentTitle';



 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  const defaultTitle = "Sonamsinrajput";
    const blurTitle = "Come Back :(";

    useDocumentTitle(defaultTitle, blurTitle);

  return (
    
    <html lang="en">
        <Head>
                <title>{defaultTitle}</title>
            </Head>
      <body>
        <Nav/>
        {children}</body>
    </html>
    
  );
}
